# default config
baseURL = "https://www.vickey-wu.com/"
languageCode = "zh-cn"
title = "吴悟无"
theme = "parsa-hugo"
summaryLength = "6"
paginate = 3

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

## navigation
#[[menu.main]]
#name = "posts"
#URL = "posts"
#weight = 2

#[[menu.main]]
#name = "share"
#URL = "share"
#weight = 3

[[menu.main]]
name = "about"
URL = "about"
weight = 4

# deult parameter
[params]
logo = "https://note.youdao.com/yws/api/personal/file/C4910B22FC3E42D5871A486C9FF8790F?method=download&shareKey=10e1d28d2d230f120165cb901aa3ea1a"
home = "Home"
# theme layout ( two layout is available, "1" and "2" )
layout = "2"
# Meta data
description = "This is meta description"
# about author
author = "Viceky Wu"
author_image = "images/banner-img.png"
bio = "大家好，我是吴悟无，90后，性别男，爱好女, 一个背锅工程师（你懂的）"
# Contact info
mobile = "+86 188 xxxx 8888"
email = "vickeywu557@qq.com"
address = "Taiwan, China"
# Contact Form Action
contact_form_action = "#"
# Google Analitycs
google_analitycs_id = "UA-160193453-1"
# copyright
copyright = "[粤ICP备20018746号-1](http://www.beian.miit.gov.cn/) Copyright &copy; 2018-2020 a theme by [parsa-hugo](https://github.com/themefisher/parsa-hugo)"
# beianhao
beianhao = "1233242"


# Preloader
[params.preloader]
enable = true

# search
[params.search]
enable = true

# social site
[[params.social]]
icon = "ti-email"
URL = "https://www.vickey-wu.com/about/"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/Vickey-Wu"
